import { InapArea, InapQuestion } from "./inapv.types.js";

export const INAPV_AREAS: InapArea[] = [
  { key: "adm", name: "Administración de Empresas y Derecho" },
  { key: "agr", name: "Agricultura, Silvicultura, Pesca y Veterinaria" },
  { key: "art", name: "Artes y Humanidades" },
  { key: "csn", name: "Ciencias Naturales, Matemática y Estadística" },
  { key: "soc", name: "Ciencias Sociales, Periodismo e Información" },
  { key: "edu", name: "Educación" },
  { key: "ing", name: "Ingeniería, Industria y Construcción" },
  { key: "sal", name: "Salud y Bienestar" },
  { key: "seg", name: "Servicios de Seguridad y Personales" },
  { key: "tec", name: "Tecnologías de la Información y Comunicación" },
];

export const INAPV_QUESTIONS: InapQuestion[] = [
  {
    id: 1,
    text: `¿Te dedicarías a aprender sobre las distintas áreas del turismo?`,
    area: "seg",
    dim: ["interes"],
  },
  {
    id: 2,
    text: `¿Te agradaría dedicar tu tiempo a ayudar a personas de sectores vulnerables?`,
    area: "soc",
    dim: ["interes"],
  },
  {
    id: 3,
    text: `En una carrera del área de la salud ¿Estudiarías día y noche hasta aprender?`,
    area: "sal",
    dim: ["aptitud"],
  },
  {
    id: 4,
    text: `¿Te gustaría dedicarte a ayudar a personas accidentadas o atacadas por asaltantes, como parte de tu trabajo?`,
    area: "seg",
    dim: ["interes", "aptitud"],
  },
  {
    id: 5,
    text: `¿Resuelves con facilidad los problemas geométricos?`,
    area: "csn",
    dim: ["aptitud"],
  },
  {
    id: 6,
    text: `¿Te gusta escuchar y ayudar a tus amigos/as y/o compañeros/as con sus problemas?`,
    area: "soc",
    dim: ["interes"],
  },
  {
    id: 7,
    text: `¿Crees tener facilidad para inspirar a un grupo de estudiantes para aprender?`,
    area: "edu",
    dim: ["aptitud"],
  },
  {
    id: 8,
    text: `¿Te agradaría trabajar cuidando la salud de animales de distintas especies?`,
    area: "agr",
    dim: ["interes", "aptitud"],
  },
  {
    id: 9,
    text: `¿Trabajarías desempeñando labores de servicio en un hotel o un spa?`,
    area: "seg",
    dim: ["interes"],
  },
  {
    id: 10,
    text: `¿Te gusta defender tus ideas para que otros te comprendan?`,
    area: "adm",
    dim: ["aptitud"],
  },
  {
    id: 11,
    text: `¿Te gusta informarte constantemente de los últimos avances en tecnología de la información y comunicación?`,
    area: "tec",
    dim: ["interes"],
  },
  {
    id: 12,
    text: `Ante una emergencia ¿Eres de los que actúa rápidamente sin bloquearse?`,
    area: "seg",
    dim: ["aptitud"],
  },
  {
    id: 13,
    text: `Al resolver un problema matemático ¿Lo intentas hasta solucionarlo?`,
    area: "csn",
    dim: ["interes", "aptitud"],
  },
  {
    id: 14,
    text: `¿Crees que tendrías facilidad para inventar y escribir un cuento?`,
    area: "art",
    dim: ["aptitud"],
  },
  {
    id: 15,
    text: `¿Te interesaría participar manteniendo el orden ante grandes desórdenes y catástrofes?`,
    area: "seg",
    dim: ["interes", "aptitud"],
  },
  {
    id: 16,
    text: `¿Te interesa leer acerca del funcionamiento de la sociedad?`,
    area: "soc",
    dim: ["interes", "aptitud"],
  },
  {
    id: 17,
    text: `¿Te gustaría saber cómo funciona un disco duro?`,
    area: "tec",
    dim: ["interes"],
  },
  {
    id: 18,
    text: `¿Disfrutas modelando con greda, arcilla u otros materiales?`,
    area: "art",
    dim: ["interes"],
  },
  {
    id: 19,
    text: `¿Te gustaría llegar a ser el/la encargado/a del área informática de una organización o empresa?`,
    area: "tec",
    dim: ["interes"],
  },
  {
    id: 20,
    text: `¿Te interesaría trabajar previniendo enfermedades?`,
    area: "sal",
    dim: ["interes"],
  },
  {
    id: 21,
    text: `¿Te interesaría aprender más sobre el comportamiento individual y social del ser humano?`,
    area: "soc",
    dim: ["interes", "aptitud"],
  },
  {
    id: 22,
    text: `¿Te llama la atención la investigación sobre los movimientos sísmicos y sus consecuencias?`,
    area: "csn",
    dim: ["interes"],
  },
  {
    id: 23,
    text: `¿Te preocupas por el cuidado del medio ambiente?`,
    area: "agr",
    dim: ["aptitud"],
  },
  {
    id: 24,
    text: `¿Te agrada resolver los problemas informáticos de familiares y/o amigos/as?`,
    area: "tec",
    dim: ["interes"],
  },
  {
    id: 25,
    text: `¿Crees que tienes facilidad para comprender conceptos informáticos? (por ejemplo: software, hardware, cable LAN)`,
    area: "tec",
    dim: ["aptitud"],
  },
  {
    id: 26,
    text: `¿Estarías dispuesto/a a renunciar a un momento agradable para acudir a prestar tus servicios como profesional de la salud?`,
    area: "sal",
    dim: ["aptitud"],
  },
  {
    id: 27,
    text: `¿Te llamaría la atención trabajar en una investigación acerca de la violencia intrafamiliar?`,
    area: "soc",
    dim: ["interes"],
  },
  {
    id: 28,
    text: `¿Te gustaría realizar experimentos químicos en un laboratorio?`,
    area: "csn",
    dim: ["interes"],
  },
  {
    id: 29,
    text: `¿Eres de los que evalúa todas las causas posibles antes de resolver un problema?`,
    area: "tec",
    dim: ["aptitud"],
  },
  {
    id: 30,
    text: `¿Te ilusiona la idea de educar personas?`,
    area: "edu",
    dim: ["interes"],
  },
  {
    id: 31,
    text: `¿Analizas todos los puntos antes de tomar una decisión?`,
    area: "adm",
    dim: ["aptitud"],
  },
  {
    id: 32,
    text: `¿Te llama la atención el diseño y construcción de edificios, puentes, etc.?`,
    area: "ing",
    dim: ["interes"],
  },
  {
    id: 33,
    text: `¿Te interesaría trabajar promoviendo el adecuado uso de los medicamentos?`,
    area: "sal",
    dim: ["interes"],
  },
  {
    id: 34,
    text: `¿Te gustaría vivir en una zona agrícola, ganadera o pesquera para trabajar ahí?`,
    area: "agr",
    dim: ["interes"],
  },
  {
    id: 35,
    text: `¿Te gusta la idea de ayudar en la transformación de la vida de las personas, a través de la educación?`,
    area: "edu",
    dim: ["interes"],
  },
  {
    id: 36,
    text: `¿Asumes rápidamente el rol de líder cuando trabajas en equipo?`,
    area: "adm",
    dim: ["aptitud"],
  },
  {
    id: 37,
    text: `¿Te llama la atención el estudio de la biología humana?`,
    area: "sal",
    dim: ["interes"],
  },
  {
    id: 38,
    text: `¿Trabajarías desarrollando proyectos de innovación y/o mejoramiento industrial?`,
    area: "ing",
    dim: ["interes"],
  },
  {
    id: 39,
    text: `¿Buscas una explicación posible a algún fenómeno de la naturaleza que no es fácil de comprender?`,
    area: "csn",
    dim: ["interes", "aptitud"],
  },
  {
    id: 40,
    text: `¿Te llama la atención la filosofía?`,
    area: "art",
    dim: ["interes"],
  },
  {
    id: 41,
    text: `¿Te gustaría trabajar resguardando el cumplimiento de la ley?`,
    area: "seg",
    dim: ["interes", "aptitud"],
  },
  {
    id: 42,
    text: `Cuando se descompone un aparato en tu casa ¿Te gusta repararlo y/o entender por qué falló?`,
    area: "ing",
    dim: ["interes", "aptitud"],
  },
  {
    id: 43,
    text: `¿Te haría feliz trabajar en un proyecto que busque la preservación de la flora y la fauna en extinción?`,
    area: "agr",
    dim: ["interes", "aptitud"],
  },
  {
    id: 44,
    text: `¿Te dedicarías a desarrollar una aplicación de celular?`,
    area: "tec",
    dim: ["interes"],
  },
  {
    id: 45,
    text: `¿Crees tener facilidad para analizar procesos culturales de una sociedad?`,
    area: "art",
    dim: ["aptitud"],
  },
  {
    id: 46,
    text: `¿Trabajarías resguardando los derechos de personas o comunidades?`,
    area: "adm",
    dim: ["interes", "aptitud"],
  },
  {
    id: 47,
    text: `¿Estarías interesado/a en trabajar en una empresa de producción agrícola, ganadera o pesquera?`,
    area: "agr",
    dim: ["interes"],
  },
  {
    id: 48,
    text: `¿Eres riguroso/a e higiénico/a para realizar labores manuales?`,
    area: "sal",
    dim: ["aptitud"],
  },
  {
    id: 49,
    text: `¿Te haría feliz trabajar ayudando a personas a llevar un estilo de vida saludable?`,
    area: "sal",
    dim: ["interes"],
  },
  {
    id: 50,
    text: `¿Trabajarías en la detección de problemas de comunicación y audición de las personas?`,
    area: "sal",
    dim: ["interes"],
  },
  {
    id: 51,
    text: `¿Lucharías por una causa justa sin darte por vencido/a?`,
    area: "adm",
    dim: ["interes", "aptitud"],
  },
  {
    id: 52,
    text: `¿Te gustaría investigar científicamente sobre innovación en el área agrícola, ganadera o pesquera?`,
    area: "agr",
    dim: ["interes"],
  },
  {
    id: 53,
    text: `¿Te haría feliz dirigir una empresa privada o pública?`,
    area: "adm",
    dim: ["interes"],
  },
  {
    id: 54,
    text: `¿Trabajarías en el área de estética y cosmética, por ejemplo, peluquería, barbería?`,
    area: "seg",
    dim: ["interes"],
  },
  {
    id: 55,
    text: `¿Te agradaría trabajar enseñando a niños, niñas y/o jóvenes?`,
    area: "edu",
    dim: ["interes"],
  },
  {
    id: 56,
    text: `¿Te gustaría diseñar un afiche para una campaña publicitaria o informativa?`,
    area: "art",
    dim: ["interes"],
  },
  {
    id: 57,
    text: `¿Te agradaría trabajar con maquinarias y/o herramientas, por ejemplo, en un taller mecánico o eléctrico?`,
    area: "ing",
    dim: ["interes", "aptitud"],
  },
  {
    id: 58,
    text: `¿Te interesaría formar parte de alguna fuerza armada o de orden y seguridad? (Ejército, Fuerza Aérea, Marina, Carabineros, PDI, Gendarmería)`,
    area: "seg",
    dim: ["interes", "aptitud"],
  },
  {
    id: 59,
    text: `¿Te agradaría trabajar en contacto directo con la tierra?`,
    area: "agr",
    dim: ["interes", "aptitud"],
  },
  {
    id: 60,
    text: `¿Eres de los que defiende a los/as compañeros/as más indefensos/as a través del diálogo?`,
    area: "adm",
    dim: ["aptitud"],
  },
  {
    id: 61,
    text: `¿Te gustaría saber cómo se heredan nuestros genes?`,
    area: "csn",
    dim: ["interes"],
  },
  {
    id: 62,
    text: `¿Escogerías una profesión cuyo principal instrumento de trabajo fuera un idioma extranjero?`,
    area: "art",
    dim: ["interes"],
  },
  {
    id: 63,
    text: `¿Ante una situación de emergencia, te gustaría ofrecerte para cuidar a un/a enfermo/a?`,
    area: "sal",
    dim: ["interes"],
  },
  {
    id: 64,
    text: `¿Te atrae la idea de estudiar los misterios del universo, por ejemplo, los agujeros negros?`,
    area: "csn",
    dim: ["interes"],
  },
  {
    id: 65,
    text: `¿Crees tener facilidad para comprender y practicar las matemáticas?`,
    area: "csn",
    dim: ["aptitud"],
  },
  {
    id: 66,
    text: `¿Prestas atención a la forma en que están decorados los lugares?`,
    area: "art",
    dim: ["interes"],
  },
  {
    id: 67,
    text: `¿Trabajarías resolviendo problemas de ingeniería en una industria?`,
    area: "ing",
    dim: ["interes"],
  },
  {
    id: 68,
    text: `¿Te gustaría saber cómo funciona la economía de nuestro país?`,
    area: "adm",
    dim: ["interes"],
  },
  {
    id: 69,
    text: `¿Trabajarías enseñando a personas con discapacidad o capacidades diferentes?`,
    area: "edu",
    dim: ["interes"],
  },
  {
    id: 70,
    text: `¿Dedicarías tu tiempo al estudio de las culturas y sociedad?`,
    area: "art",
    dim: ["interes", "aptitud"],
  },
  {
    id: 71,
    text: `¿Escogerías una profesión en la que las principales herramientas de trabajo fueran la lectura y escritura?`,
    area: "soc",
    dim: ["interes", "aptitud"],
  },
  {
    id: 72,
    text: `¿Te llama la atención trabajar en el área financiera?`,
    area: "adm",
    dim: ["interes"],
  },
  {
    id: 73,
    text: `¿Te gustaría trabajar en una investigación científica que permita desarrollar productos más amigables con el medio ambiente?`,
    area: "csn",
    dim: ["interes"],
  },
  {
    id: 74,
    text: `¿Trabajarías en una empresa dedicada a la producción agrícola, ganadera o pesquera sustentable?`,
    area: "agr",
    dim: ["interes"],
  },
  {
    id: 75,
    text: `¿Estudiarías una carrera dedicada al manejo de tecnología de la información y comunicación?`,
    area: "tec",
    dim: ["interes"],
  },
  {
    id: 76,
    text: `¿Te gustaría trabajar diseñando circuitos automatizados?`,
    area: "ing",
    dim: ["interes", "aptitud"],
  },
  {
    id: 77,
    text: `¿Estudiarías una carrera dedicada a la salud bucal de las personas?`,
    area: "sal",
    dim: ["interes"],
  },
  {
    id: 78,
    text: `¿Te agradaría trabajar atendiendo personas en el área turística o estética?`,
    area: "seg",
    dim: ["interes"],
  },
  {
    id: 79,
    text: `¿Se te hace fácil explicar a tus compañeros/as una temática que no entiendan?`,
    area: "edu",
    dim: ["aptitud"],
  },
  {
    id: 80,
    text: `¿Convencerías fácilmente a un compañero/a acerca de una idea, utilizando únicamente el diálogo?`,
    area: "soc",
    dim: ["aptitud"],
  },
  {
    id: 81,
    text: `¿Crees tener facilidad para comprender las ciencias básicas, por ejemplo, química o biología?`,
    area: "csn",
    dim: ["interes", "aptitud"],
  },
  {
    id: 82,
    text: `¿Tienes un método o forma específica para hacer cada cosa?`,
    area: "agr",
    dim: ["aptitud"],
  },
  {
    id: 83,
    text: `¿Crees que tendrías aptitudes para detener el ataque informático de un hacker?`,
    area: "tec",
    dim: ["aptitud"],
  },
  {
    id: 84,
    text: `¿Te das cuenta rápidamente cuando hay una situación de riesgo o peligro?`,
    area: "seg",
    dim: ["aptitud"],
  },
  {
    id: 85,
    text: `¿Te interesaría estudiar cómo mejorar el aprendizaje de niños, niñas y/o jóvenes?`,
    area: "edu",
    dim: ["interes"],
  },
  {
    id: 86,
    text: `¿Sientes inclinación por aprender sobre historia universal y/o de América?`,
    area: "art",
    dim: ["interes"],
  },
  {
    id: 87,
    text: `¿Dedicas tiempo a informarte sobre noticias de actualidad?`,
    area: "soc",
    dim: ["interes", "aptitud"],
  },
  {
    id: 88,
    text: `¿Participarías de una investigación dedicada al cuidado de animales en extinción?`,
    area: "agr",
    dim: ["interes", "aptitud"],
  },
  {
    id: 89,
    text: `¿Trabajarías en el desarrollo de proyectos de tecnología de la información?`,
    area: "tec",
    dim: ["interes"],
  },
  {
    id: 90,
    text: `¿Consideras importante la solución de problemas en la industria?`,
    area: "ing",
    dim: ["interes"],
  },
  {
    id: 91,
    text: `¿Te interesaría aprender sobre la gastronomía de distintas culturas?`,
    area: "seg",
    dim: ["interes"],
  },
  {
    id: 92,
    text: `¿Crees tener facilidad para mantener la calma ante un grupo de niños, niñas o jóvenes de un curso, frente una situación difícil?`,
    area: "edu",
    dim: ["aptitud"],
  },
  {
    id: 93,
    text: `¿Crees tener facilidad para analizar y comprender problemas sociales?`,
    area: "soc",
    dim: ["aptitud"],
  },
  {
    id: 94,
    text: `¿Crees que tendrías facilidad para trabajar con animales?`,
    area: "agr",
    dim: ["aptitud"],
  },
  {
    id: 95,
    text: `¿Consideras que tienes facilidad para resolver problemas informáticos?`,
    area: "tec",
    dim: ["aptitud"],
  },
  {
    id: 96,
    text: `¿Te llama la atención trabajar en un contexto educativo como una sala de clases y/o un patio escolar?`,
    area: "edu",
    dim: ["interes"],
  },
  {
    id: 97,
    text: `¿Te interesa aprender sobre política nacional e internacional?`,
    area: "soc",
    dim: ["interes", "aptitud"],
  },
  {
    id: 98,
    text: `¿Te agrada la idea de dedicarte a resolver problemas matemáticos?`,
    area: "csn",
    dim: ["interes", "aptitud"],
  },
  {
    id: 99,
    text: `¿Dedicarías tu tiempo para comprender la relación de la ciencia con el mundo que nos rodea?`,
    area: "csn",
    dim: ["interes"],
  },
  {
    id: 100,
    text: `¿Estudiarías una carrera que se dedique al cuidado del bosque nativo?`,
    area: "agr",
    dim: ["interes", "aptitud"],
  },
  {
    id: 101,
    text: `¿Trabajarías identificando las necesidades de usuarios de un programa informático (Software)?`,
    area: "tec",
    dim: ["interes", "aptitud"],
  },
  {
    id: 102,
    text: `¿Te gustaría armar tu propio computador?`,
    area: "tec",
    dim: ["interes"],
  },
  {
    id: 103,
    text: `¿Te gustaría trabajar en el área de producción de una empresa?`,
    area: "ing",
    dim: ["interes"],
  },
];
